### PR TITLE
Added experimental messaging system.

### PR DESCRIPTION
**Pull request by tustvold**
I've created a PR for this as I'm not sure whether it is a good idea. The main goal is to decouple the producers of data from the consumers. For example, the sensor drivers don't need to know who actually uses the data they produce, they simply send it off to the messaging system and it then delivers it to the components that have registered interest (e.g state estimation, SD card logging, USB interface, etc.).

The system has a number of advantages:
- Decouples components - producers of data don't need to know what consumes said data
- Simplifies component design, particularly those that aggregate data from multiple sources (e.g state estimation), by handling a lot of the concurrent work
- Prevents duplication of mailbox management code
- Ensures that producer threads aren't accidentally held up by work being done in other components - previously a sensor providing the state estimation system with new data might have to wait for a whole kalman update step to perform. This ensures that can't happen.
- Very simple to create bidirectional USB/RS232/CAN/SPI interfaces and enable/disable them
- The SD card logging will necessarily capture all the data - not just what components explicitly log
- Isolates component failure. If a component fails it won't prevent other parts of the system from functioning. For example, if SD logging deadlocks other components can continue to operate, whereas previously they would deadlock when trying to log.

It does, however, have some disadvantages:
- Adds a single point of failure, the failure of which may be hard to detect
- Has performance implications but these should be minor
- Makes it harder to follow/reason about program flow

### CODE REVIEW

**Comment by rjw57** [comment]
I'm away today but will look at this ASAP. First impressions: concept good, not yet looked at implementation.

**Comment by tustvold** [comment]
This could also be nicely integrated into martlet 3 with packets sent out on the CAN bus simply fed into the messaging system, although I think we might run out of room in the channel byte.

**Comment by adamgreig** [comment]
I haven't looked through the rest of the messaging system but the new packet format caught my eye. I don't think it's worth doubling the size of each packet for the benefits you list, but you may disagree, so I'll outline my reasoning:

To handle protocols such as USB where larger packets are more efficient, you might as well just use a buffer - sending two small packets at once is then just as easy as one of these large packets, and you get twice the packet rate (even if the same amount of payload data). The obvious flip side is that for protocols where small packets are more efficient - like radio links, where you have doubled the chance of a packet error, or like CAN bus, with its 8 byte payloads - you make the situation much worse.

With the larger origin, source, and tags you accommodate up to 16 thousand software components on each of 16 thousand hardware devices with 255 different tags and then 255 different data modes. It seems like perhaps it would be more useful to have a bit more payload data instead. I won't be so brave as to say we'll never need 16 thousand devices, but 255 seems enough for the forseeable future...

The 32 bit timestamp wrapping around is annoying, but we compensate for it in desktop software where doing so is easy and we're not very resource constrained. The hardware device still uses a 32 bit timer internally, so the overflow will still happen - just now you have to compensate for it by storing another 32 bit overflow counter on the hardware, and copying both into your telemetry message each time. For 4 bytes of useful data I don't think the convenience of simpler analysis software is worthwhile.

4 floats at once: I can't argue with this, it's obviously really useful. Previously we had to use two messages to contain a four-long float vector which was less good. However, the majority of messages did fit in one payload field.

I don't think the original Martlet 2 packet format was particularly great (putting the checksum in the middle was an obvious mistake), and the one in Badger 3 is better, so I'm very interested in having a conversation about how to make a good format. My experience last time was that basically the packets were too big for the data (50% header information!) which really crippled things like high rate ADC and IMU sampling. I wonder if a variable size packet, where you might have a few hundred samples associated with one header that could contain information on rate and time, would give us better performance while satisfying your goals of working better over USB etc.

Perhaps it would be worth studying a few other telemetry packet systems deployed in the field first. There are some very good references available - for example the CCSDS publications, where perhaps 132.0-B-2  is specifically relevant, or perhaps see what PSAS do, documented here: https://github.com/psas/psas_packet. What we do in Martlet 3 will be informed by what you do here, but also what we've done in the past, our use of CAN (and its 8 byte payloads), and anything we learn in the interim, so it's a good time to come up with something nice...

I'll try and look over the other messaging system stuff sometime but no promises!

**Comment by tustvold** [comment]
Unless anyone has any objections I'm going to merge this in tomorrow as the point of the PR (to determine if this was a good idea) I think has been fulfilled? It has also sufficiently diverged from master that if people start working on master, the merge is going to be painful.

**Pull request merged**
